### ISSUE TITLE
Startup problem

### ISSUE THREAD

**Issue by macoshaxor1111** [Karmaz95/Snake_Apple#1]
When I try to run it against arm64 mach-o binary I get:

```
TypeError: __eq__(): incompatible function arguments. The following argument types are supported:
    1. __eq__(self, arg: lief._lief.Object, /) -> bool

Invoked with types: lief._lief.MachO.Binary, NoneType
```

The command I used:
```
python3 CrimsonUroboros -p Safari
```

**Comment by Karmaz95** [comment]
The latest patch [6e4376a](https://github.com/Karmaz95/Snake_Apple/commit/6e4376adbc620d6a00dc62f0739450df081a44d8) addresses the issue you mentioned. Please update the tool (clone the latest repository) to resolve it.

The issue existed because of the newest patch to the `lief` library, on which this program depends. The vendor of the `lief` library changed some properties in the Python API, so I had to patch some functions in the `CrimsonUroboros`.

If you want to see what has changed, please visit this [commit 6e4376a](https://github.com/Karmaz95/Snake_Apple/commit/6e4376adbc620d6a00dc62f0739450df081a44d8).

I conducted tests, and it seems that all functions work as expected.
<img width="1511" alt="image" src="https://github.com/Karmaz95/Snake_Apple/assets/51202595/7d76fd9e-f779-42c3-ad76-45694e4fa887">

If you need further assistance, please comment below.
